"""Generate Markdown reports from scan sessions or aggregated payloads."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from blhackbox.models.base import ScanSession
from blhackbox.reporting.html_generator import SEVERITY_ORDER
from blhackbox.reporting.paths import get_report_path

if TYPE_CHECKING:
    from blhackbox.models.aggregated_payload import AggregatedPayload

logger = logging.getLogger("blhackbox.reporting.md_generator")


def _severity_emoji(sev: str) -> str:
    return {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🟢",
        "info": "🔵",
    }.get(sev.lower(), "⚪")


def generate_md_report(
    session: ScanSession,
    output_path: str | None = None,
) -> Path:
    """Generate a Markdown report from a scan session.

    Args:
        session: Completed scan session with findings.
        output_path: Override output file path.

    Returns:
        Path to the generated Markdown file.
    """
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    findings_sorted = sorted(
        session.findings,
        key=lambda f: SEVERITY_ORDER.get(
            f.severity if isinstance(f.severity, str) else f.severity.value, 99
        ),
    )

    severity_counts = session.severity_counts
    total_findings = len(session.findings)

    lines: list[str] = []
    lines.append("# Blhackbox Security Assessment Report")
    lines.append("")
    lines.append(f"**Target:** {session.target.value}  ")
    lines.append(f"**Session:** {session.id}  ")
    lines.append(f"**Date:** {generated_at}  ")
    if session.duration_seconds is not None:
        lines.append(f"**Duration:** {session.duration_seconds:.1f}s  ")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        lines.append(f"| {_severity_emoji(sev)} {sev.upper()} | {count} |")
    lines.append("")

    # Tools Executed
    lines.append("## Tools Executed")
    lines.append("")
    if session.tools_executed:
        for tool in session.tools_executed:
            lines.append(f"- `{tool}`")
    else:
        lines.append("_No tools recorded._")
    lines.append("")

    # Findings
    lines.append(f"## Findings ({total_findings})")
    lines.append("")

    for finding in findings_sorted:
        sev = finding.severity if isinstance(finding.severity, str) else finding.severity.value
        lines.append(f"### {_severity_emoji(sev)} {finding.title}")
        lines.append("")
        lines.append(f"**Severity:** {sev.upper()}  ")
        lines.append(f"**Tool:** {finding.tool}  ")
        lines.append("")

        if finding.description:
            desc = finding.description[:3000]
            lines.append("**Description:**")
            lines.append("```")
            lines.append(desc)
            lines.append("```")
            lines.append("")

        if finding.evidence:
            evidence = finding.evidence[:2000]
            lines.append("**Evidence:**")
            lines.append("```")
            lines.append(evidence)
            lines.append("```")
            lines.append("")

        if finding.remediation:
            lines.append(f"> **Remediation:** {finding.remediation}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.append("*Generated by Blhackbox v2.0.0 – MCP-based Autonomous Pentesting Framework*  ")
    lines.append("*This report is confidential. Unauthorized distribution is prohibited.*")
    lines.append("")

    md_content = "\n".join(lines)

    if output_path:
        out = Path(output_path)
    else:
        out = get_report_path(session.target.value, "md")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md_content, encoding="utf-8")
    logger.info("Markdown report generated: %s", out)
    return out


def generate_md_report_from_payload(
    payload: AggregatedPayload,
    output_path: str | None = None,
) -> Path:
    """Generate a Markdown report from an AggregatedPayload.

    Args:
        payload: Aggregated pentest data from the aggregator MCP server.
        output_path: Override output file path.

    Returns:
        Path to the generated Markdown file.
    """
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    vulns = sorted(
        payload.findings.vulnerabilities,
        key=lambda v: SEVERITY_ORDER.get(v.severity.lower(), 99),
    )

    severity_counts: dict[str, int] = {}
    for v in vulns:
        sev = v.severity.lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    anomalies = [
        e for e in payload.error_log
        if e.security_relevance in ("medium", "high")
    ]

    lines: list[str] = []
    lines.append("# Blhackbox Security Assessment Report")
    lines.append("")
    lines.append(f"**Target:** {payload.target}  ")
    lines.append(f"**Session:** {payload.session_id}  ")
    lines.append(f"**Date:** {generated_at}  ")
    lines.append("")

    if payload.metadata.warning:
        lines.append(f"> **Warning:** {payload.metadata.warning}")
        lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        lines.append(f"| {_severity_emoji(sev)} {sev.upper()} | {count} |")
    lines.append("")

    # Tools & Agents
    lines.append("## Tools & Agents")
    lines.append("")
    for tool in payload.metadata.tools_run:
        lines.append(f"- `{tool}`")
    lines.append("")

    # Vulnerabilities
    lines.append(f"## Vulnerabilities ({len(vulns)})")
    lines.append("")

    for vuln in vulns:
        title = vuln.title or vuln.id or vuln.description[:60]
        lines.append(f"### {_severity_emoji(vuln.severity.lower())} {title}")
        lines.append("")
        lines.append(f"**Severity:** {vuln.severity.upper()}  ")
        lines.append(f"**Host:** {vuln.host}  ")
        if vuln.cvss:
            lines.append(f"**CVSS:** {vuln.cvss}  ")
        lines.append("")

        desc = vuln.description[:3000]
        lines.append("```")
        lines.append(desc)
        lines.append("```")
        lines.append("")

        if vuln.references:
            lines.append("**References:** " + ", ".join(vuln.references))
            lines.append("")

        lines.append("---")
        lines.append("")

    # Network Hosts
    if payload.findings.hosts:
        lines.append(f"## Network Hosts ({len(payload.findings.hosts)})")
        lines.append("")
        for host in payload.findings.hosts:
            lines.append(f"### {host.ip}")
            lines.append("")
            lines.append("```")
            for p in host.ports:
                lines.append(f"{p.port}/{p.state} {p.service} {p.version}")
            lines.append("```")
            lines.append("")

    # Anomalies
    if anomalies:
        lines.append("## Anomalies & Scan Artifacts")
        lines.append("")
        for a in anomalies:
            lines.append(
                f"- **[{a.type}]** Count: {a.count}"
                f" | Relevance: {a.security_relevance}"
                f" — {a.security_note}"
            )
        lines.append("")

    # Scan Metadata
    lines.append("## Scan Metadata")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Raw Size (bytes) | {payload.metadata.total_raw_size_bytes} |")
    lines.append(f"| Compression Ratio | {payload.metadata.compression_ratio:.2f} |")
    lines.append(f"| Model | {payload.metadata.model} |")
    lines.append(f"| Duration | {payload.metadata.duration_seconds:.1f}s |")
    lines.append("")

    # Footer
    lines.append("*Generated by Blhackbox v2.0 – MCP-based Autonomous Pentesting Framework*  ")
    lines.append("*This report is confidential. Unauthorized distribution is prohibited.*")
    lines.append("")

    md_content = "\n".join(lines)

    if output_path:
        out = Path(output_path)
    else:
        out = get_report_path(payload.target, "md")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md_content, encoding="utf-8")
    logger.info("Markdown report (aggregated) generated: %s", out)
    return out
